version: '3.8'

services:
  notification-service:
    build: 
      context: .
      target: build
    container_name: notification-service
    ports:
      - "8091:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run -Dspring-boot.run.profiles=docker
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - bookstore-network

networks:
  bookstore-network:
    external: true
