apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://bookstore-db-do-user-36177370-0.h.db.ondigitalocean.com:25060/bookstore_notification?useSSL=true&requireSSL=true&serverTimezone=UTC"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  USER_SERVICE_URL: "http://user-service:8080"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
